permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Kelvin
  email: yaokaifei@sina.com
  link: http://tecpoet.com
  weibo: http://weibo.com/1629641415/profile?topnav=1&wvr=6
  github: http://github.com/yaokaifei
  music: http://www.douban.com/people/yaokaifei/
  linkedin: http://www.linkedin.com/profile/view?id=413264785&trk=hp-identity-name

# 站点信息
title: 姚凯飞的博客
description: My personal blog
url: http://tecpoet.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: tecpoet.com

# disqus 设置
disqus:
  shortname: tecpoet

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Machine Learning
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档